### ISSUE TITLE
Not working with jsx when tag contains self closing component.

### ISSUE THREAD

**Issue by kristijanhusak** [AndrewRadev/tagalong.vim#1]
Hi,

I just tried using a plugin in jsx file (React app), and it's not working properly when jsx contains self closing component. Here's an example code:

```jsx
import React from 'react';
import MyCustomComponent from './MyCustomComponent';

class Test extends React.Component {
  render() {
    return (
      <div className="main">
        <div className="testing">
          <MyCustomComponent />
        </div>
      </div>
    )
  }
}
```

Changing `div` in line with `className="main"`, changes it only on that line, and changing `div` in line with `className="testing"` changes that line, and the last closing div tag. Self closing component (`<MycustomComponent />`) confuses it. When i change it to `<MyCustomComponent></MyCustomComponent>` everything works fine.

**Comment by AndrewRadev** [comment]
Thanks for reporting -- I thought that removing the matchit dependency would have unfortunate side-effects, we'll see what else shows up :).

I've pushed a potential fix. Could you try it out and let me know if it works for you?

**Comment by kristijanhusak** [comment]
Looks good now. Thanks for the quick fix! :)
