### ISSUE TITLE
Add support for react fragments

### ISSUE THREAD

**Issue by hughcrt** [AndrewRadev/tagalong.vim#12]
Hi,

Do you think it would be possible to add support for [react fragment short syntax](https://reactjs.org/docs/fragments.html) (`<> </>`)?

**Comment by AndrewRadev** [comment]
There's probably going to be a few scenarios to handle. For now, I've pushed an experimental branch, [react-fragment-support](https://github.com/AndrewRadev/tagalong.vim/tree/react-fragment-support). With this example:

``` jsx
class Columns extends React.Component {
  render() {
    return (
      <>
        <td>Hello</td>
        <td>World</td>
      </>
    );
  }
}
```

Going in the opening brackets, entering insert mode with `i` and typing `foobar` ought to change the closing tag as well.

One problem is that this doesn't work when entering insert mode with `a`. This seems to be a general problem, so something I need to take a look at.

What other cases do you think should be handled? I'm thinking that moving from a named component to an "anonymous" one makes sense, so maybe `dt>` should also remove the closing tag. Does this make sense and can you think of other scenarios? How do you usually change fragments with this short syntax?

**Comment by hughcrt** [comment]
Well done for your work!

The two use cases are:
- jsx tag -> fragment
- fragment -> jsx tag

So I believe adding `dt>` to remove the closing tag would be nice to have

**Comment by AndrewRadev** [comment]
I've added support for deletion with `d` to the branch -- it should also work for stuff like `dw`, `di>` etc. Really, all `d` motions that change the tag. The logic is slightly different from what the plugin usually does, so please try it out for a while, to see if there's any issues. The tests are passing, but a lot of things could go wrong that I haven't thought of :).

**Comment by hughcrt** [comment]
Great. I'll start to use it and I'll let you know if I find any bug!

**Comment by hughcrt** [comment]
I found one small bug. If there is no tag between the fragment, changing the opening fragment to a named tagged doesn't change the closing fragment.
It works fine if there's already an element between the fragments, and changing the closing fragment to an named has the expected effect.

There's not many use cases in React where you would only return a fragment without anything inside. But I use some shortcuts to generate empty react components, like this:

```javascript
function MyComponent() {
   return (
       <>
      
       </>
   )
}
```

Changing the name of fragments without children would make sense in this case

**Comment by AndrewRadev** [comment]
Good catch, I see that one of my regexes wasn't quite working the way I expected it to work -- I've pushed a fix.

**Comment by hughcrt** [comment]
I haven't had any problem since you pushed the fix. I think you can merge!
