### ISSUE TITLE
add `gohtmltmpl` to default file types

### ISSUE THREAD

**Issue by mrjones2014** [AndrewRadev/tagalong.vim#13]
the `vim-go` plugin adds niceties for the `gohtmltmpl` Go HTML Template file type, commonly used by the Hugo static site generator.

**Comment by AndrewRadev** [comment]
Cool -- added it to the defaults :+1:. Let me know if you run into any issues.

**Comment by mrjones2014** [comment]
works perfectly, thank you! this plugin is awesome, thanks for your work!
