### ISSUE TITLE
Cannot enter Visual mode

### ISSUE THREAD

**Issue by AlexisFinn** [AndrewRadev/tagalong.vim#15]
when I hit `v` in Normal mode to enter Visual mode, I get an error:
```
E5107: Error loading lua [string ":luaa.]:1: unexpected symbol near '\'
:call tagalong#Trigger("
```
and so if I hit `viw` to select current word i get the same error with the `iw` entered as parameters for `tagalong#Trigger(`
```
E5107: Error loading lua [string ":luaa.]:1: unexpected symbol near '\'
:call tagalong#Trigger("iw
```

**Comment by AlexisFinn** [comment]
```
:version
NVIM v0.5.0-dev+1414-g8cdffd42d
Build type: Release
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/cc -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -DNDEBUG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict
-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-commo
n -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -
DMIN_LOG_LEVEL=3 -I/home/alexis/Applications/neovim/build/config -I/home/alexis/Applications/neovim/src -I/home/alexis/Application
s/neovim/.deps/usr/include -I/usr/include -I/home/alexis/Applications/neovim/build/src/nvim/auto -I/home/alexis/Applications/neovi
m/build/include
```

**Comment by AndrewRadev** [comment]
Hm, I just tried it on `NVIM v0.5.0-dev+1421-ga72dfec85`, and I can enter visual mode just fine, so I can't reproduce the issue with just this information.

How do you install and load the plugin? What I put in `.config/nvim/init.vim` is:

``` vim
call plug#begin('~/.local/share/nvim/plugged')

Plug 'AndrewRadev/tagalong.vim'

call plug#end()
```

I think there might be something about the loading process, because the message says "Error loading lua". I think for some reason, it's trying to evaluate vimscript as lua, but I don't know why. Could you share your neovim config and how you've set the plugin up?

**Comment by rbozan** [comment]
I have the same problem. Pressing `v` or even attempting to change a tag results in the following
```
E5107: Error loading lua [string ":lua"]:1: unexpected symbol near '\'
:call tagalong#Trigger("
```

**Comment by AndrewRadev** [comment]
I tried building Neovim from source, since I know there was a recent PR merged that allows lua config to be loaded -- I thought maybe it's related? But I still can't replicate it with this version:

```

**Comment by AndrewRadev** [comment]
One thing you could to in order to at least avoid breaking `v` is to exclude it from the "mappings" list by putting this in your config:

``` vim
let g:tagalong_mappings = ['c', 'C', 'i', 'a']
```

This doesn't solve the issue, of course, and I would appreciate if you keep experimenting so we can figure it out.

**Comment by rbozan** [comment]
> I tried building Neovim from source, since I know there was a recent PR merged that allows lua config to be loaded -- I thought maybe it's related? But I still can't replicate it with this version:
> 
> ```
> :version                                                                                                                                 
> NVIM v0.5.0-dev+1425-g7da86f55a
> Build type: RelWithDebInfo
> LuaJIT 2.1.0-beta3
> ```
> 
> Could it be a temporary bug that was fixed? Could you try updating to the latest master and trying it out again?
> 
> I also tried `:help E5107`, but I'm getting `E149: Sorry, no help for E5107`, so I don't know how to approach debugging the problem :/

I actually remember that I had this exact problem a few months ago when trying out Neovim 0.5 for the first time, so it is not a recent problem. I tried to debug it a bit for you, and it seems when I include https://github.com/folke/which-key.nvim in my config, it actually seems to break this plugin. 


```
call plug#begin()
Plug 'AndrewRadev/tagalong.vim'
Plug 'folke/which-key.nvim'
call plug#end()

lua << EOF
  require("which-key").setup {}
EOF
```

**Comment by AndrewRadev** [comment]
Interesting. Runninng `:checkhealth which_key` does give me this:

```
health#which_key#check
========================================================================
## WhichKey: checking conflicting keymaps
  - WARNING: buffer-local keymap overriding global for mode **"n"**, buf: 0, lhs: **"c"**
  - INFO: old rhs: `:<c-u>call tagalong#Trigger("c", v:count)<cr>`
  - INFO: new rhs: `<cmd>lua require("which-key").show("c", {mode = "n", auto = true})<cr>`
  - WARNING: buffer-local keymap overriding global for mode **"n"**, buf: 0, lhs: **"v"**
  - INFO: old rhs: `:<c-u>call tagalong#Trigger("v", v:count)<cr>`
  - INFO: new rhs: `<cmd>lua require("which-key").show("v", {mode = "n", auto = true})<cr>`
```

So there's a conflict in mappings, although it theoretically shouldn't be a problem. Weirdly, I *still* can't replicate the issue even with your above config.

One possibility I'm considering is that it's related to tagalong's behaviour of trying to maintain mappings. Basically, if there's already a mapping for `v` from the config or from some other plug, it'll try to execute it -- this is probably what's happening here, that tagalong is executing a command that's executing lua code and this is somehow getting messed up. Once again, can't quite replicate it, so hard to say for sure.

Could you execute `:map v` and show me the results? Here's what I see on my neovim installation:

```
n  v           *@:<C-U>call tagalong#Trigger("v", v:count)<CR>                                                                          
n  viÞ         * <Nop>
n  vaÞ         * <Nop>
n  vÞ          * <Nop>
n  v           * <Cmd>lua require("which-key").show("v", {mode = "n", auto = true})<CR>
```

**Comment by rbozan** [comment]
Mine shows:
```
n  v           *@:<C-U>call tagalong#Trigger("<Cmd>lua require(\"which-key\").show(\"v\", {mode = \"n\", auto = true})<CR>", v:count)<CR>
n  vaÞ         * <Nop>
n  viÞ         * <Nop>
n  vÞ          * <Nop>
n  v           * <Cmd>lua require("which-key").show("v", {mode = "n", auto = true})<CR>
```

**Comment by AndrewRadev** [comment]
I think I understand what the problem is. It seems like Neovim has something called `<Cmd>`, which just aborts the current command-line and does its thing. I think maybe I could get it to work if I replace it with `:`, but I'm not sure if this won't cause unfortunate side effects. Feels like the safest thing to do is to avoid nesting it. I've pushed a commit that does this, could you try it out?

**Comment by rbozan** [comment]
> I think I understand what the problem is. It seems like Neovim has something called `<Cmd>`, which just aborts the current command-line and does its thing. I think maybe I could get it to work if I replace it with `:`, but I'm not sure if this won't cause unfortunate side effects. Feels like the safest thing to do is to avoid nesting it. I've pushed a commit that does this, could you try it out?

Yep it works! Thank you.

**Comment by AndrewRadev** [comment]
Great, thanks for helping with the debugging process.

@AlexisFinn Could you try pulling the latest version as well?

**Comment by AlexisFinn** [comment]
Wow, @rbozan @AndrewRadev thanks for looking into this issue so quickly and efficiently.
Sorry I didn't watch this issue so intently as I must admit I can live without tagalong.

So it's a conflict with `which-key`, I kinda figured it was something like that (I mean surely this would have been spotted otherwise).
Ill try pulling the latest version and see if it works immediately.

**Comment by AlexisFinn** [comment]
Seems to work fine now. Great work, thanks alot.

Closing this issue since it's solved.

**Comment by AndrewRadev** [comment]
Awesome, thanks for checking :+1:
