### ISSUE TITLE
Doesn't work in <c-v> mode.

### ISSUE THREAD

**Issue by singlexyz** [AndrewRadev/tagalong.vim#17]
![ezgif-2-8fbc69ce6ffc](https://user-images.githubusercontent.com/4456413/124451978-8a5cf180-ddb8-11eb-9117-21463f63fdad.gif)

But the fun part is, I can change one, then use `.` to repeat

It works. 😍

**Comment by AndrewRadev** [comment]
Unfortunately, I can't think of a way to handle this case. The plugin works on individual tags and this kind of batch-editing wouldn't really work. I can see the idea -- if the tags start at the same position but end in different ones, blockwise visual mode would be easy for the start, but not the end. But I can only recommend the `.` method, I'm afraid.

I'll close this for now as a "won't fix" until I get an unlikely future burst of inspiration :)
