### ISSUE TITLE
Not working with single letter tags such as <a>, <p>, etc...

### ISSUE THREAD

**Issue by tricarte** [AndrewRadev/tagalong.vim#2]
Thanks for the plugin. It's probably because of my vimrc but it doesn't work with single letter tags. It works fine with tags with two or more letters though.

**Comment by AndrewRadev** [comment]
It's not your vimrc, I managed to reproduce the problem. I noticed and fixed it at some point, but I ended up changing regexes, and there was a regression :).

Pushed a fix (and wrote a test this time), please try it out and let me know if it works for you.

**Comment by tricarte** [comment]
Seems fixed. Thank you.
