### ISSUE TITLE
Plugin not working, unsure if I installed it correctly.

### ISSUE THREAD

**Issue by stalris** [AndrewRadev/tagalong.vim#22]
I'm new to using plugins, so I apologize if this question seems trivial. The plugin doesn't work for me at all. Whenever I alter a tag the corresponding tag isn't affected. I asked on StackOverflow what could have gone wrong and they told me to check the paths returned by the command `:set runtimepath?`. The following is the result `  runtimepath=~/vimfiles,~\vimfiles\plugged\tagalong.vim,C:\Program Files (x86)\Vim/vimfiles,C:\Program Files (x86)\Vim\vim90,C:\Program Files (x86)\Vim/vimfiles/after,~/vimfiles/after`.

Any idea how I could troubleshoot my problem? Thanks!

**Comment by AndrewRadev** [comment]
The plugin is only activated for certain filetypes, so the first thing to check if it's active. The runtimepath seems like it includes it, but to check directly:

- Open an html file
- Check if it's detected as html by executing `:set filetype?`
- Check `nmap c`, one of the lines of the output should include `n  c           *@:<C-U>call tagalong#Trigger("c", v:count)<CR>`

Could you try these out and see if any of the steps fails?

**Comment by stalris** [comment]
Turns out my problem was using the delete command instead of the change command to edit text, woops. I thought entering insert mode immediately after using delete would trigger the plugin but I was mistaken. Thanks for the help!

**Comment by AndrewRadev** [comment]
Ah, I see. You *might* be able to get that to work, but I haven't tried it myself. You could check out `:help tagalong-internals` for an overview of how you could use the plugin's tools directly: https://github.com/AndrewRadev/tagalong.vim/blob/5a2bbf2b1d5b657685a49d48d98a4aa921c1fde3/doc/tagalong.txt#L265-L279

But you do mention you're new to using plugins, so I assume new to vimscript in general. Maybe something to keep in mind for later.
