### ISSUE TITLE
Case-only changes are ignored

### ISSUE THREAD

**Issue by dlee** [AndrewRadev/tagalong.vim#8]
It seems like renaming a tag name to one with a different case is being ignored (e.g. `<link>` to `<Link>`). If this is intentional, then it would be nice to have an option to support case-sensitive change detection.

**Comment by AndrewRadev** [comment]
It's a bug -- an oversight on my part. I'm assuming in your config you have `set ignorecase`, and I didn't consider it. Thankfully, it's an easy fix -- let me know if it works correctly for you now.

**Comment by dlee** [comment]
That fixed it. Thanks!
