### ISSUE TITLE
Add vue filetype to the defaults

### ISSUE THREAD

**Issue by Eduruiz** [AndrewRadev/tagalong.vim#9]
First, thanks for your work here, I just find out this plugin and it looks really good!
I use Vue a lot and think it will be a great addition to the default filetypes list, I added it in the
```
let g:tagalong_additional_filetypes = ['vue']
```
and it's working as it should! :)

**Comment by AndrewRadev** [comment]
Makes sense -- I've added the `vue` filetype to the default list :+1:
